name: PhotoQuizz
options:
  bundleIdPrefix: com.photoquizz
  deploymentTarget:
    tvOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  PhotoQuizz:
    type: application
    platform: tvOS
    sources:
      - path: PhotoQuizz
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.photoquizz.app
        INFOPLIST_FILE: PhotoQuizz/Info.plist
        PRODUCT_NAME: PhotoQuizz
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        GENERATE_INFOPLIST_FILE: false
    info:
      path: PhotoQuizz_src/Info.plist
      properties:
        CFBundleDisplayName: PhotoQuizz
        CFBundleName: PhotoQuizz
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: ""
        NSPhotoLibraryUsageDescription: "PhotoQuizz needs access to your photo library to create personalized memory games from your geotagged travel photos."
